### ISSUE TITLE
STD_LOG_COLLECTION_PORT & LOGS_CONFIG variables

### ISSUE THREAD

**Issue by lmmendes** [lmmendes/datadog_buildpack#6]
We should allow people to specify `STD_LOG_COLLECTION_PORT` and `LOGS_CONFIG`  `source` attribute.

Where `STD_LOG_COLLECTION_PORT` value should match the `LOGS_CONFIG`  `port` attribute.

And `LOGS_CONFIG` `source` attribute should also have a default, eg: `pcf` but be able to be defined in case users wish to `change` the configuration of their `logback-spring.xml` and have a different playload.

```
      STD_LOG_COLLECTION_PORT: 10514
      LOGS_CONFIG: '[{"type":"tcp","port":"10514","source":"pcf-source-v1", "service":" nebula-sandbox-app"}]'
```

Question, should be search for a `LOGS_CONFIG_SOURCE` in the vcap service variables and if not set we would default to `pcf`?

**Comment by cfcfs** [comment]
The defaults can be overridden, but other than that I would keep it simple and not allow individual values of LOGS_CONFIG to be set. 
I would just change the default source to pcf and the default port to STD_LOG_COLLECTION_PORT.
